Bryan Martinez

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Populating Dataset
dataset = pd.read_csv(r'C:\Users\Bryan Martinez\react\prowrestleknow\DataCollector\RawResults.csv', encoding='ISO-8859-1')
dataset.head(30)

,company,show,year,month,day,competitors,winners,wins_by,stipulations,on_the_line,duration
0,WWE,Raw,2024,June,3,"Ludwig Kaiser, Sheamus",Ludwig Kaiser,pinfall,none,none,TBD
1,WWE,Raw,2024,June,3,"Finn Balor, Dragon Lee",Finn Balor,pinfall,none,none,TBD
2,WWE,Raw,2024,June,3,"Bron Breakker, Ricochet",Bron Breakker,pinfall,none,none,TBD
3,WWE,Raw,2024,June,3,"Kiana James, Natalya",Kiana James,pinfall,none,none,TBD
4,WWE,Raw,2024,June,3,"Braun Strowman, Carlito",Braun Strowman,pinfall,none,none,TBD
5,WWE,Raw,2024,June,3,"Bianca Belair, Jade Cargill, Shayna Bazler, Zo...","Bianca Belair, Jade Cargill",DQ,none,WWE Womens Tag Team Championship,TBD
6,WWE,Raw,2024,June,3,"Akam, Rezar, Kofi Kingston, Xavier Woods","Akam, Rezar",pinfall,none,none,TBD
7,WWE,Raw,2024,June,3,"Damian Priest, Rey Mysterio",Damian Priest,pinfall,none,none,TBD
8,WWE,NXT,2024,June,4,"Jordynne Grace, Stevie Turner",Jordynne Grace,pinfall,none,none,TBD
9,WWE,NXT,2024,June,4,"Jazmyn Nyx, Thea Hail",Jazmyn Nyx,pinfall,none,none,TBD
10,WWE,NXT,2024,June,4,"Damon Kemp, Tony D'Angelo",Tony D'Angelo,pinfall,British Round Rules,NXT Hertiage Cup,TBD
11,WWE,NXT,2024,June,4,"Izzi Dame, Natalya",Natalya,pinfall,none,none,TBD
12,WWE,NXT,2024,June,4,"Fallon Henley, Kelani Jordan, Lash Legend, Jai...","Jaida Parker, Mia Yim, Sol Ruca",pinfall,none,none,TBD
13,AEW,Dynamite,2024,June,5,"Orange Cassidy, Kyle O'Reilly, Jay Lethal, Rey...",Rey Fenix,pinfall,Fatal Four Way Match,none,TBD
14,AEW,Dynamite,2024,June,5,"Mark Briscoe, Brian Cage",Mark Briscoe,pinfall,none,none,TBD
15,AEW,Dynamite,2024,June,5,"Bryan Danielson, Claudio Castagnoli, Jon Moxle...","Bryan Danielson, Claudio Castagnoli, Jon Moxle...",pinfall,8-Man Grudge Match,none,TBD
16,AEW,Dynamite,2024,June,5,"Saraya (Paige), Mariah May",Saraya (Paige),submission,none,none,TBD
17,AEW,Dynamite,2024,June,5,"Swerve Strickland, Roderick Strong",Swerve Strickland,pinfall,none,none,TBD

In [3]:
# Dataset Columns
dataset.columns

Index(['company', 'show', 'year', 'month', 'day', 'competitors', 'winners',
       'wins_by', 'stipulations', 'on_the_line', 'duration'],
      dtype='object')

In [4]:
# Checking for Null Data
dataset.isnull().sum()

company         0
show            0
year            0
month           0
day             0
competitors     0
winners         0
wins_by         0
stipulations    0
on_the_line     0
duration        0
dtype: int64

In [5]:
all_names = set()
for competitors in dataset['competitors']:
    names = competitors.split(', ')
    all_names.update(names)

# Create a new DataFrame with the competitor names
filtered_dataset = pd.DataFrame({'wrestler_name': list(all_names)})

In [6]:
competitor_counts = {}
for name in all_names:
    if name in competitor_counts:
        competitor_counts[name] += 1
    else:
        competitor_counts[name] = 1

# Create DataFrame for competitor counts
filtered_dataset = pd.DataFrame({'competitor_name': list(competitor_counts.keys()), 'count': list(competitor_counts.values())})
filtered_dataset.head(60)

                competitor_name  count
0                Jordynne Grace      1
1                    Damon Kemp      1
2                  Wheeler Yuta      1
3                 Kofi Kingston      1
4                 Tony D'Angelo      1
5                Braun Strowman      1
6                 Bron Breakker      1
7                 Shayna Bazler      1
8                         Rezar      1
9                      Sol Ruca      1
10             Astro Boy Magnus      1
11                         Akam      1
12                Bianca Belair      1
13                   Jon Moxley      1
14                  Volador Jr.      1
15           Claudio Castagnoli      1
16               Orange Cassidy      1
17                Ludwig Kaiser      1
18                  Kiana James      1
19  Rugido (La Parka Negra III)      1
20                   Jazmyn Nyx      1
21                    Thea Hail      1
22                Fallon Henley      1
23                   Brian Cage      1
24                   Jay Lethal      1
25                Kelani Jordan      1
26                   Mariah May      1
27              Bryan Danielson      1
28                 Jade Cargill      1
29                Stevie Turner      1
30              Roderick Strong      1
31                 Rey Mysterio      1
32                Damian Priest      1
33                      Carlito      1
34                      Natalya      1
35                 Mark Briscoe      1
36                   Zoey Stark      1
37                      Sheamus      1
38                Kyle O'Reilly      1
39                     Ricochet      1
40                   Finn Balor      1
41                  Lash Legend      1
42                      Mia Yim      1
43               Saraya (Paige)      1
44                 Xavier Woods      1
45                    Izzi Dame      1
46                 Jaida Parker      1
47  Esfinge (HalcÃ³n Furia Jr.)      1
48            Swerve Strickland      1
49                   Dragon Lee      1
50                    Rey Fenix      1

# Final Results Gets Saved to New CSV File

In [7]:

filtered_dataset.to_csv('../../../src/Data/TeamInfo.csv', index=False, encoding='ISO-8859-1')